export const assignments = [
    {
        assignment_id: 1,
        learning_content_ids: [1],
        new_learning_content: null,
        class_ids: [1],
        other_student_ids: [3, 6], 
        due_date: new Date("2025-03-10"),
        assigned_date: new Date("2025-03-01"),
        timer: null,
        max_submissions: 2,
        allow_late_submissions: true,
    },
    {
        assignment_id: 2,
        learning_content_ids: null,
        new_learning_content: {
            title: "SAT Algebra Mastery",
            short_description: "Key algebraic techniques and problem-solving approaches for SAT success.",
            type: "Exercise",
            areas: ["Math"],
            sub_areas: {
                Math: ["Algebra"],
            },
        },
        class_ids: [2],
        other_student_ids: [1, 5], 
        due_date: new Date("2025-03-15"),
        assigned_date: new Date("2025-03-05"),
        timer: 3600, 
        max_submissions: 1,
        allow_late_submissions: false,
    },
    {
        assignment_id: 3,
        learning_content_ids: [5, 8],
        new_learning_content: null,
        class_ids: [3],
        other_student_ids: [2], 
        due_date: new Date("2025-03-12"),
        assigned_date: new Date("2025-03-02"),
        timer: 5400,
        max_submissions: 3,
        allow_late_submissions: true,
    },
    {
        assignment_id: 4,
        learning_content_ids: null,
        new_learning_content: {
            title: "Reading Comprehension Techniques",
            short_description: "Strategies to improve reading speed and comprehension for SAT Verbal.",
            type: "Document",
            areas: ["Verbal"],
            sub_areas: {
                Verbal: ["Information and Ideas"],
            },
        },
        class_ids: [1, 2],
        other_student_ids: [8, 9], 
        due_date: new Date("2025-03-20"),
        assigned_date: new Date("2025-03-10"),
        timer: null,
        max_submissions: 2,
        allow_late_submissions: true,
    },
    {
        assignment_id: 5,
        learning_content_ids: [3],
        new_learning_content: null,
        class_ids: [2, 3],
        other_student_ids: [11], 
        due_date: new Date("2025-03-18"),
        assigned_date: new Date("2025-03-08"),
        timer: 7200,
        max_submissions: 1,
        allow_late_submissions: false,
    },
    {
        assignment_id: 6,
        learning_content_ids: [10],
        new_learning_content: null,
        class_ids: [1],
        other_student_ids: [13, 14], 
        due_date: new Date("2025-03-22"),
        assigned_date: new Date("2025-03-12"),
        timer: null,
        max_submissions: 3,
        allow_late_submissions: true,
    },
    {
        assignment_id: 7,
        learning_content_ids: null,
        new_learning_content: {
            title: "SAT Geometry and Trigonometry",
            short_description: "Key concepts and formulas for tackling SAT geometry and trigonometry questions.",
            type: "Document",
            areas: ["Math"],
            sub_areas: {
                Math: ["Geometry and Trigonometry"],
            },
        },
        class_ids: [3],
        other_student_ids: [6, 10], 
        due_date: new Date("2025-03-25"),
        assigned_date: new Date("2025-03-15"),
        timer: 4800,
        max_submissions: 2,
        allow_late_submissions: false,
    },
    {
        assignment_id: 8,
        learning_content_ids: [9],
        new_learning_content: null,
        class_ids: [2],
        other_student_ids: [12], 
        due_date: new Date("2025-03-28"),
        assigned_date: new Date("2025-03-18"),
        timer: 3600,
        max_submissions: 1,
        allow_late_submissions: true,
    },
    {
        assignment_id: 9,
        learning_content_ids: null,
        new_learning_content: {
            title: "SAT Writing: Common Grammar Mistakes",
            short_description: "A detailed guide to common SAT grammar mistakes and how to avoid them.",
            type: "Document",
            areas: ["Verbal"],
            sub_areas: {
                Verbal: ["Standard English Conventions"],
            },
        },
        class_ids: [1, 3],
        other_student_ids: [7], 
        due_date: new Date("2025-03-30"),
        assigned_date: new Date("2025-03-20"),
        timer: null,
        max_submissions: 2,
        allow_late_submissions: true,
    },
    {
        assignment_id: 10,
        learning_content_ids: [6, 7],
        new_learning_content: null,
        class_ids: [2, 3],
        other_student_ids: [4], 
        due_date: new Date("2025-04-05"),
        assigned_date: new Date("2025-03-25"),
        timer: 6000,
        max_submissions: 1,
        allow_late_submissions: false,
    },
];
