const assignments = [
  {
      assignment_id: 1,
      learning_content_id: 1,
      new_learning_content: null,
      class_ids: [1],
      other_student_ids: [],
      due_date: new Date("2025-03-10"),
      assigned_date: new Date("2025-03-01"),
      timer: "01:30:00",
      max_submissions: 2,
      allow_late_submissions: false,
  },
  {
      assignment_id: 2,
      learning_content_id: 3,
      new_learning_content: null,
      class_ids: [2],
      other_student_ids: [5, 8],
      due_date: new Date("2025-03-12"),
      assigned_date: new Date("2025-03-02"),
      timer: null,
      max_submissions: 3,
      allow_late_submissions: true,
  },
  {
      assignment_id: 3,
      learning_content_id: 5,
      new_learning_content: null,
      class_ids: [1, 3],
      other_student_ids: [],
      due_date: new Date("2025-03-15"),
      assigned_date: new Date("2025-03-05"),
      timer: "01:45:00",
      max_submissions: 1,
      allow_late_submissions: false,
  },
  {
      assignment_id: 4,
      learning_content_id: 7,
      new_learning_content: null,
      class_ids: [3],
      other_student_ids: [1, 6],
      due_date: new Date("2025-03-18"),
      assigned_date: new Date("2025-03-08"),
      timer: "02:30:00",
      max_submissions: 2,
      allow_late_submissions: true,
  },
  {
      assignment_id: 5,
      learning_content_id: null,
      new_learning_content: {
          title: "Probability Mastery Challenge",
          short_description: "A set of problems to test and enhance understanding of probability concepts.",
          type: "Exercise",
          areas: ["Math"],
          sub_areas: {
              Math: ["Probability & Statistics"],
          },
      },
      class_ids: [],
      other_student_ids: [2, 4, 9, 13],
      due_date: new Date("2025-03-20"),
      assigned_date: new Date("2025-03-10"),
      timer: "01:00:00",
      max_submissions: 1,
      allow_late_submissions: false,
  },
  {
      assignment_id: 6,
      learning_content_id: 10,
      new_learning_content: null,
      class_ids: [2, 3],
      other_student_ids: [],
      due_date: new Date("2025-03-22"),
      assigned_date: new Date("2025-03-12"),
      timer: "01:15:00",
      max_submissions: 2,
      allow_late_submissions: false,
  },
  {
      assignment_id: 7,
      learning_content_id: null,
      new_learning_content: {
          title: "Mastering Algebraic Expressions",
          short_description: "Practice simplifying and manipulating algebraic expressions.",
          type: "Exercise",
          areas: ["Math"],
          sub_areas: {
              Math: ["Algebra"],
          },
      },
      class_ids: [1],
      other_student_ids: [3, 7],
      due_date: new Date("2025-03-25"),
      assigned_date: new Date("2025-03-15"),
      timer: "01:00:00",
      max_submissions: 3,
      allow_late_submissions: true,
  },
  {
      assignment_id: 8,
      learning_content_id: null,
      new_learning_content: {
          title: "Essential SAT Vocabulary",
          short_description: "Flashcards covering the most frequently tested SAT vocabulary words.",
          type: "Flashcard",
          areas: ["Vocab"],
          sub_areas: {},
      },
      class_ids: [2],
      other_student_ids: [5, 6],
      due_date: new Date("2025-03-28"),
      assigned_date: new Date("2025-03-18"),
      timer: null,
      max_submissions: 1,
      allow_late_submissions: false,
  },
  {
      assignment_id: 9,
      learning_content_id: 51,
      new_learning_content: null,
      class_ids: [3],
      other_student_ids: [],
      due_date: new Date("2025-03-30"),
      assigned_date: new Date("2025-03-20"),
      timer: "02:00:00",
      max_submissions: 2,
      allow_late_submissions: true,
  },
  {
      assignment_id: 10,
      learning_content_id: null,
      new_learning_content: {
          title: "SAT Writing: Grammar Rules Review",
          short_description: "A document summarizing key SAT grammar rules with examples.",
          type: "Document",
          areas: ["Verbal"],
          sub_areas: {
              Verbal: ["Standard English Conventions"],
          },
      },
      class_ids: [],
      other_student_ids: [1, 4, 8],
      due_date: new Date("2025-04-02"),
      assigned_date: new Date("2025-03-22"),
      timer: "01:45:00",
      max_submissions: 2,
      allow_late_submissions: true,
  },
];
